<a href="https://colab.research.google.com/github/Zncl2222/MachineLearningPractice/blob/pytorch_tutorial/pytorch_tutorial/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu121


In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix (commonly as upper case in machine learning and deep learning)
MATRIX = torch.tensor([[2, 3, 4],
            [2, 5, 6]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[1])

# Tensor (commonly as upper case in machine learning and deep learning)

tensor([[2, 3, 4],
        [2, 5, 6]])
2
torch.Size([2, 3])
tensor([2, 5, 6])


In [ ]:
# Create a random tensor
random_tensor = torch.rand(3, 1, 4)
print(random_tensor)
print(random_tensor.ndim)

random_tensor = torch.rand(3, 4)
print(random_tensor)
print(random_tensor.ndim)

tensor([[[0.0860, 0.7261, 0.2369, 0.6241]],

        [[0.5658, 0.9349, 0.0962, 0.5058]],

        [[0.1531, 0.3228, 0.3695, 0.2015]]])
3
tensor([[0.8594, 0.3189, 0.5213, 0.8378],
        [0.0850, 0.1132, 0.3011, 0.0650],
        [0.8204, 0.6423, 0.0249, 0.2534]])
2


In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))  # height, witdht, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# Create ones and zeor tensor
zero_tensor = torch.zeros((3, 5, 2), dtype=int)
ones_tensor = torch.ones((2, 2), dtype=float)
zero_tensor.shape, zero_tensor.dtype, ones_tensor.shape, ones_tensor.dtype

(torch.Size([3, 5, 2]), torch.int64, torch.Size([2, 2]), torch.float64)

In [ ]:
# Arange
arange_tensor = torch.arange(1, 10, 1)
arange_tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Create tensors like
ten_zeros = torch.zeros_like(input=arange_tensor)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor(
  [3.0, 6.0, 9.0],
  dtype=None,
  device=None,
  requires_grad=False
)

float_64_tensor = torch.tensor(
  [3.0, 6.0, 9.0],
  dtype=torch.float64,
  device=None,
  requires_grad=False
)

print(float_32_tensor, float_32_tensor.dtype, float_32_tensor.device)
print(float_64_tensor, float_64_tensor.dtype, float_64_tensor.device)

tensor([3., 6., 9.]) torch.float32 cpu
tensor([3., 6., 9.], dtype=torch.float64) torch.float64 cpu


In [ ]:
flaot_16_tensor = float_32_tensor.type(torch.float16)
print(flaot_16_tensor, flaot_16_tensor.dtype, flaot_16_tensor.device)

tensor([3., 6., 9.], dtype=torch.float16) torch.float16 cpu


In [ ]:
new_tensor = flaot_16_tensor * float_32_tensor
new_tensor.dtype

torch.float32

In [ ]:
# Manipulating Tensors
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor - 6

tensor([-5, -4, -3])

In [ ]:
tensor.mul(10)

tensor([10, 20, 30])

In [ ]:
tensor.add(12)

tensor([13, 14, 15])

In [ ]:
tensor.sub(123)

tensor([-122, -121, -120])

In [ ]:
tensor.div(2)

tensor([0.5000, 1.0000, 1.5000])

In [ ]:
# Mat mul
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [ ]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 622 µs, sys: 0 ns, total: 622 µs
Wall time: 2.07 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 412 µs, sys: 74 µs, total: 486 µs
Wall time: 2.71 ms


tensor(14)

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
              [3, 4],
              [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
              [8, 11],
              [9, 12]], dtype=torch.float32)

In [ ]:
# These three are same
print(tensor_A @ tensor_B.T)
print(tensor_A.matmul(tensor_B.T))
print(tensor_A.mm(tensor_B.T))

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


In [ ]:
tensor_A.mean()

tensor(3.5000)

In [ ]:
torch.sum(tensor_A), tensor_A.sum()

(tensor(21.), tensor(21.))

In [ ]:
# Finding the positional min and masx
tensor_A.argmin(), tensor_A.argmax()

(tensor(0), tensor(5))

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Use clone to ensure reshape can use the copy
x_reshaped = x.reshape(1, 9).clone()
print(x_reshaped, x_reshaped.shape)

x_reshaped[:, 0] = 5
print(x_reshaped, x)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [ ]:
# view shared the memory of the original input
z = x.view(1, 9)
print(z, z.shape, x, x.shape)

z[:, 0] = 5
print(z, x)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9]) tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [ ]:
x_stacked = torch.stack([x, x ,x ,x ], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
v_stacked = torch.vstack([x, x])
v_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
h_stacked = torch.hstack([x, x])
h_stacked

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x = torch.zeros(2, 1, 2, 1, 2)
print(x, x.size())

y = x.squeeze()
print(y, y.size())

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]]) torch.Size([2, 1, 2, 1, 2])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]) torch.Size([2, 2, 2])


In [ ]:
y2 = y.unsqueeze(dim=0)
print(y2.shape)

y3 = y.unsqueeze(dim=1)
print(y3.shape)

y4 = y.unsqueeze(dim=2)
print(y4.shape)

torch.Size([1, 2, 2, 2])
torch.Size([2, 1, 2, 2])
torch.Size([2, 2, 1, 2])


In [ ]:
x = torch.rand(size=(224, 224, 3))
print(x.size())
x.permute(dims=(2, 0 ,1)).size()  # shifts the index 2 to 0, 0 to 1 and 1 to 2

torch.Size([224, 224, 3])


torch.Size([3, 224, 224])

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
print(x[0])
print(x[0][0])
print(x[0, 0])
print(x[0][-1][-1])
print(x[0, -1, -1])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor(9)
tensor(9)


In [ ]:
print(x[:, 0])
print(x[0, 0, :])

tensor([[1, 2, 3]])
tensor([1, 2, 3])


In [ ]:
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
print(array, tensor)
print(array.dtype, tensor.dtype)

[1. 2. 3. 4. 5. 6. 7.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
float64 torch.float64


In [ ]:
# Default dtype of numpy is float64 and pytorch is float32
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Set random seed for pytorch tensor
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C, '\n', random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


In [ ]:
# Start using GPU
!nvidia-smi

Sat Mar  9 07:03:49 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
torch.cuda.is_available()
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [ ]:
tensor_on_gpu.to('cpu').numpy()

array([1, 2, 3])