<a href="https://colab.research.google.com/github/Zncl2222/MachineLearningPractice/blob/pytorch_tutorial/00_pytorch_fundamentals_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Exercise1
Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.


#### Exercise2
Create a random tensor with shape (7, 7).

In [1]:
import torch

tensor = torch.rand(size=(7, 7))
tensor

tensor([[0.4279, 0.5260, 0.6442, 0.0946, 0.8218, 0.4946, 0.4604],
        [0.7183, 0.2247, 0.4648, 0.6661, 0.7739, 0.0592, 0.4168],
        [0.6216, 0.8256, 0.5386, 0.5871, 0.0882, 0.2693, 0.8291],
        [0.9338, 0.8786, 0.0810, 0.9722, 0.0681, 0.2928, 0.3483],
        [0.1466, 0.3005, 0.0100, 0.9138, 0.0801, 0.4617, 0.5666],
        [0.2809, 0.1868, 0.7565, 0.6641, 0.4781, 0.3702, 0.5200],
        [0.8726, 0.7145, 0.1622, 0.7112, 0.2732, 0.6751, 0.9106]])

#### Exercise3
Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [13]:
zero_tensor = torch.rand(size=(1, 7))
result_tensor = tensor.reshape(49, 1).matmul(zero_tensor)
result_tensor

tensor([[6.0124e-02, 2.5806e-01, 5.5850e-02, 1.5454e-01, 1.3955e-02, 4.0442e-01,
         1.2000e-01],
        [3.5169e-02, 1.5095e-01, 3.2669e-02, 9.0394e-02, 8.1630e-03, 2.3656e-01,
         7.0195e-02],
        [2.2874e-02, 9.8177e-02, 2.1248e-02, 5.8793e-02, 5.3092e-03, 1.5386e-01,
         4.5655e-02],
        [1.0265e-01, 4.4056e-01, 9.5350e-02, 2.6383e-01, 2.3825e-02, 6.9045e-01,
         2.0487e-01],
        [3.4579e-02, 1.4841e-01, 3.2121e-02, 8.8877e-02, 8.0260e-03, 2.3259e-01,
         6.9017e-02],
        [1.1700e-01, 5.0218e-01, 1.0869e-01, 3.0073e-01, 2.7157e-02, 7.8702e-01,
         2.3353e-01],
        [3.6562e-02, 1.5693e-01, 3.3964e-02, 9.3976e-02, 8.4864e-03, 2.4594e-01,
         7.2976e-02],
        [5.3424e-02, 2.2930e-01, 4.9626e-02, 1.3731e-01, 1.2400e-02, 3.5935e-01,
         1.0663e-01],
        [1.0233e-01, 4.3921e-01, 9.5057e-02, 2.6302e-01, 2.3752e-02, 6.8833e-01,
         2.0424e-01],
        [5.8450e-02, 2.5087e-01, 5.4295e-02, 1.5023e-01, 1.3567e-02, 3.93

#### Exercise4
Set the random seed to 0 and do exercises 2 & 3 over again.

In [14]:
RAND_SEED = 123
torch.manual_seed(RAND_SEED)
tensor_a = torch.rand(7, 7)
torch.manual_seed(RAND_SEED)
tensor_b = torch.rand(1, 7)

tensor_c = tensor_a.reshape(49, 1).mm(tensor_b)
tensor_c

tensor([[0.0877, 0.1530, 0.0745, 0.2039, 0.0219, 0.2566, 0.0404],
        [0.1530, 0.2668, 0.1300, 0.3557, 0.0382, 0.4476, 0.0706],
        [0.0745, 0.1300, 0.0633, 0.1733, 0.0186, 0.2181, 0.0344],
        [0.2039, 0.3557, 0.1733, 0.4741, 0.0509, 0.5966, 0.0940],
        [0.0219, 0.0382, 0.0186, 0.0509, 0.0055, 0.0641, 0.0101],
        [0.2566, 0.4476, 0.2181, 0.5966, 0.0641, 0.7509, 0.1183],
        [0.0404, 0.0706, 0.0344, 0.0940, 0.0101, 0.1183, 0.0187],
        [0.0303, 0.0529, 0.0258, 0.0706, 0.0076, 0.0888, 0.0140],
        [0.0545, 0.0951, 0.0463, 0.1267, 0.0136, 0.1595, 0.0251],
        [0.2151, 0.3753, 0.1828, 0.5002, 0.0537, 0.6295, 0.0992],
        [0.0934, 0.1628, 0.0793, 0.2171, 0.0233, 0.2732, 0.0431],
        [0.2035, 0.3549, 0.1729, 0.4731, 0.0508, 0.5954, 0.0938],
        [0.0224, 0.0391, 0.0190, 0.0521, 0.0056, 0.0655, 0.0103],
        [0.0582, 0.1016, 0.0495, 0.1354, 0.0145, 0.1704, 0.0269],
        [0.0937, 0.1634, 0.0796, 0.2179, 0.0234, 0.2742, 0.0432],
        [0

#### Exercise5
Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [2]:
RAND_SEED = 654
torch.cuda.manual_seed(RAND_SEED)
gpu_tensor = torch.rand((3, 3), device='cuda')
torch.cuda.manual_seed(RAND_SEED)
gpu_tensor2 = torch.rand((3, 3), device='cuda')
gpu_tensor, gpu_tensor2

(tensor([[0.5826, 0.1039, 0.7702],
         [0.8087, 0.5020, 0.7764],
         [0.8980, 0.8438, 0.3329]], device='cuda:0'),
 tensor([[0.5826, 0.1039, 0.7702],
         [0.8087, 0.5020, 0.7764],
         [0.8980, 0.8438, 0.3329]], device='cuda:0'))

#### Exercise6
Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [6]:
RAND_SEED = 1234
torch.manual_seed(RAND_SEED)
tensor = torch.rand((2, 3), device='cpu')
gpu_tensor = tensor.to('cuda')
torch.manual_seed(RAND_SEED)
tensor2 = torch.rand((2, 3), device='cpu')
gpu_tensor2 = tensor.to('cuda')
gpu_tensor, gpu_tensor2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

#### Exercise7
Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [7]:
reshaped_tensor = gpu_tensor.reshape(3, 2)

result_tensor = reshaped_tensor.mm(gpu_tensor2)
result_tensor, result_tensor.shape

(tensor([[0.1482, 0.0351, 0.2891],
         [0.1420, 0.1258, 0.3244],
         [0.2586, 0.0643, 0.5061]], device='cuda:0'),
 torch.Size([3, 3]))

#### Exercise 8 & 9
Find the maximum and minimum values of the output of 7.
Find the maximum and minimum index values of the output of 7.

In [8]:
print(result_tensor.max())
print(result_tensor.min())
print(result_tensor.argmax())
print(result_tensor.argmin())

tensor(0.5061, device='cuda:0')
tensor(0.0351, device='cuda:0')
tensor(8, device='cuda:0')
tensor(1, device='cuda:0')


#### Exercise 10
Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [12]:
torch.manual_seed(7)
tensor = torch.rand(size=(1, 1, 1, 10))
tensor_squeezed = tensor.squeeze()
print(tensor, tensor.shape)
print(tensor_squeezed, tensor_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
